version: '2'
services:
  web:
    build: .
    ports:
      - 4300:4300
      - 4302:4302
    volumes:
      - ./:/usr/src/app
    environment:
      JEKYLL_ENV: "development"
    command: bundle exec jekyll serve --watch --host 0.0.0.0 --port 4300 --trace --incremental --livereload --livereload-port 4302
